Should throw an error if the mode is not recognized

diff --git a/wrappers/java/wrapper b/wrappers/java/wrapper
--- a/wrappers/java/wrapper
+++ b/wrappers/java/wrapper
@@ -5,6 +5,14 @@ module=$2
 fd_in=$3
 fd_out=$4
 debug=$5
+
+read -r -d '' usage << "EOF"
+Usage:
+        $0 compile module_name
+        $0 run module_name fd_in fd_out debug
+        $0 version
+EOF
+
 # change to java subdirectory
 cd $(dirname $0)
 if [ "$action" == "version" ]; then
@@ -27,4 +35,8 @@ elif [ "$action" == "run" ]; then
 	echo "Running $module $fd_int $fd_out with classpath $CLASSPATH in $PWD"
 	#java -cp "lib/*" org.ensembl.hive.Wrapper "$module" "$pipe_in" "$pipe_out" "$debug"
     ant -Dorg.ensembl.hive.module=$module -Dorg.ensembl.hive.pipe_in=$fd_in -Dorg.ensembl.hive.pipe_out=$fd_out -Dorg.ensembl.hive.debug=$debug run_wrapper
+else
+	echo "Command-line error: No mode provided"
+	echo "$usage"
+	exit 1
 fi
